# Generated by Django 6.0.5 on 2026-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_persona"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="persona",
            options={"verbose_name": "persona", "verbose_name_plural": "personas"},
        ),
        migrations.AlterField(
            model_name="persona",
            name="apellidos",
            field=models.CharField(max_length=100, verbose_name="Apellidos"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="biografia",
            field=models.TextField(verbose_name="Biografía"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="correo",
            field=models.EmailField(max_length=254, verbose_name="Correo Electrónico"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="dedicacion",
            field=models.CharField(max_length=200, verbose_name="Dedicación"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="direccion",
            field=models.CharField(max_length=200, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="nombres",
            field=models.CharField(max_length=100, verbose_name="Nombres"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="telefono",
            field=models.CharField(max_length=20, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="titulo_academico",
            field=models.CharField(max_length=200, verbose_name="Título Académico"),
        ),
    ]
